### DATA ENDPOINT FOR ADDING A USER
POST http://localhost:8383/api/signup
Content-Type: application/json

{
    "username": "tongi",
    "password": "tongimexico"
}

### DATA ENDPOINT FOR LOGIN
POST http://localhost:8383/api/login
Content-Type: application/json

{
    "username": "sheik",
    "password": "sheik7pro"
}

### TEST SERVER CONNECTION
GET http://localhost:8383/api/test

### VIEW ALL USERS
GET http://localhost:8383/api/users

###TEST THE GET MESSAGES API
GET http://localhost:8383/api/messages/1/2